apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  type: ClusterIP
  selector:
    app: appointment-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085